services:
  web:
    container_name: web-prod
    build:
      context: ./apps/web
      dockerfile: prod.Dockerfile
      args:
        ENV_VARIABLE: ${ENV_VARIABLE}
        NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    restart: always
    ports:
      - 3000:3000
    networks:
      - host_network
    depends_on:
      - jobs

  jobs:
    container_name: jobs-prod
    build:
      context: ./apps/jobs
      dockerfile: prod.Dockerfile
    volumes:
      - /data/delivery/ssh/keys:/var/ssh/keys
    restart: always
    ports:
      - 3090:3090
    networks:
      - host_network

networks:
  host_network:
    name: host_network
    driver: bridge
