services:
  web:
    container_name: web
    build:
      context: ./packages/web
      dockerfile: prod.Dockerfile
      args:
        ENV_VARIABLE: ${ENV_VARIABLE}
        NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    restart: always
    ports:
      - 3000:3000
    networks:
      - my_network
    depends_on:
      - jobs

  jobs:
    container_name: jobs
    build:
      context: ./packages/jobs
      dockerfile: prod.Dockerfile
    volumes:
      - /data/delivery/ssh:/var/ssh
    restart: always
    networks:
      - my_network

networks:
  my_network:
    external: true
