services:
  web:
    build:
      context: ./apps/web
      dockerfile: prod.Dockerfile
    env_file:
      - .env.web
      args:
        ENV_VARIABLE: ${ENV_VARIABLE}
        NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    volumes:
      - ./apps/web/src:/app/src
    restart: always
    ports:
      - 3000:3000
    networks:
      - host_network
    depends_on:
      - jobs

  jobs:
    build:
      context: ./apps/jobs
      dockerfile: prod.Dockerfile
    env_file:
      - .env.jobs
    volumes:
      - /data/delivery/ssh/keys:/var/ssh/keys
    restart: always
    ports:
      - 3090:3090
    networks:
      - host_network

networks:
  host_network:
    name: host_network
    driver: bridge
