export const WEBHOOK_EVENTS = [
  { id: "push", label: "code is pushed to a branch" },
  { id: "pull_request", label: "a pull request is opened, updated, merged, or closed" },
  { id: "release", label: "a release is published, updated, or deleted" },
  { id: "workflow_run", label: "a GitHub Actions workflow is completed" },
  { id: "deployment", label: "a new deployment is created" },
  { id: "deployment_status", label: "a deployment status is updated" },
  { id: "repository", label: "a repository is created, renamed, transferred, or deleted" },
  { id: "issues", label: "an issue is opened, edited, closed, reopened, assigned, labeled, or unlocked" },
  { id: "issue_comment", label: "an issue comment is created, edited, or deleted" },
  { id: "pull_request_review", label: "a pull request review is submitted, edited, or dismissed" },
  { id: "pull_request_review_comment", label: "a comment is created, edited, or deleted on a pull request" },
  { id: "commit_comment", label: "a commit comment is created" },
  { id: "create", label: "a branch or tag is created" },
  { id: "delete", label: "a branch or tag is deleted" },
  { id: "fork", label: "the repository is forked" },
  { id: "public", label: "a repository is made public" },
  { id: "star", label: "a user stars or unstars the repository" },
  { id: "watch", label: "a user starts or stops watching the repository" },
  { id: "check_run", label: "a check run is created, rerequested, or completed" },
  { id: "check_suite", label: "a check suite is completed, requested, or rerequested" },
  { id: "page_build", label: "a Pages site is built or fails to build" },
  { id: "repository_vulnerability_alert", label: "a security vulnerability alert is created, dismissed, or resolved" },
  { id: "security_advisory", label: "a security advisory is published, updated, or withdrawn" },
  { id: "sponsorship", label: "a sponsorship is created, updated, or cancelled" },
  { id: "team", label: "a team is created, modified, or deleted" },
  { id: "team_add", label: "a team is added to a repository" },
  { id: "member", label: "a user is added, removed, or invited as a repository collaborator" },
  { id: "membership", label: "a user is added or removed from a team" },
  { id: "label", label: "a label is created, edited, or deleted" },
  { id: "milestone", label: "a milestone is created, updated, closed, or deleted" },
  { id: "project", label: "a project is created, updated, closed, or deleted" },
  { id: "project_card", label: "a project card is created, edited, moved, or deleted" },
  { id: "project_column", label: "a project column is created, edited, moved, or deleted" },
  { id: "organization", label: "an organization event occurs (user invited, renamed, deleted, etc.)" },
  { id: "installation", label: "a GitHub App is installed or uninstalled" },
  { id: "installation_repositories", label: "a repository is added or removed from an installation" },
  { id: "status", label: "the status of a commit changes" },
];
