---
# accessLog: {}  # uncomment this line to enable access log
log:
  level: WARN  # ERROR, DEBUG, PANIC, FATAL, ERROR, WARN, INFO
providers:
  swarm:
    exposedByDefault: false
    endpoint: "unix:///var/run/docker.sock"
    network: proxy
  file:
    filename: /etc/traefik/dynamic.yaml
    watch: true
api:
  dashboard: true # if you don't need the dashboard disable it
entryPoints:
  web:
    address: ':80' # http
    #http:
    #  redirections:
    #    entryPoint:
    #      to: web-secure
    #      scheme: https
  web-secure:
    address: ':443' # https
certificatesResolvers:
  deliveryresolver:
    acme:
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory # IMPORTANT: comment out this line to get production ready certificates. After this, clear acme.json file.
      email: pedoy59842@nutrv.com
      storage: /etc/traefik/acme.json
      httpChallenge:
        entryPoint: web
global:
  checkNewVersion: true
  sendAnonymousUsage: true # disable this if you don't want to send anonymous usage data to traefik