name: Release

on:
  workflow_run:
    workflows: ["Tests"]
    branches: [main, next]
    types: [completed]

jobs:
  cd:
    name: Update registry images on release
    runs-on: ubuntu-latest
    environment: production

    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
      AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
      JOBS_API_BASEURL: ${{ vars.JOBS_API_BASEURL }}
      JOBS_BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
      PORT: ${{ vars.PORT }}
      LOG_LEVEL: ${{ vars.LOG_LEVEL }}
      BASE_URL: ${{ vars.BASE_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: pnpm/action-setup@v4
        name: Install pnpm

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Release
        run: npx -p @semantic-release/exec semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push images
        uses: docker/bake-action@v6
        if: env.docker_publish == 'true'
        with:
          push: true
          files: ./compose.prod.yaml