name: Monorepo Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app:
          - jobs
          - web

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: |
          cd apps/${{ matrix.app }}
          npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.app }}
          path: apps/${{ matrix.app }}/dist

  test:
    runs-on: self-hosted
    environment: test
    env:
      NODE_ENV: ${{ vars.NODE_ENV }}
      LOG_LEVEL: ${{ vars.LOG_LEVEL }}
      PORT: ${{ vars.PORT }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
    needs: build
    strategy:
      matrix:
        app:
          - jobs
          - web

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-${{ matrix.app }}
          path: apps/${{ matrix.app }}/dist

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: |
          cd apps/${{ matrix.app }}
          npm test

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.app }}
          path: apps/${{ matrix.app }}/coverage
