name: Push images to registry

on:
  workflow_run:
    workflows: ["Running UT/E2E and IT tests"]
    types:
      - completed
    branches: ["main"]

jobs:
  push-to-registry:
    runs-on: ubuntu-latest
    environment: production

    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push images
        run: |
          docker compose build
          docker compose push
