name: Push images to registry

on:
  workflow_run:
    workflows: ["Running unit/integration tests"]
    types:
      - completed
    branches: ["main", "next"]

jobs:
  push-to-registry:
    runs-on: ubuntu-latest
    # environment: production (uncomment when repo go to public)

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
      AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
      JOBS_BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
      PORT: 9030
      LOG_LEVEL: silent
      JOBS_API_BASEURL: http://localhost:3090
      NEXT_PUBLIC_BASEURL: http://localhost:3000

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Release
        run: npx -p @semantic-release/exec semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push images
        if: github.env.docker_publish == 'true'
        run: |
          docker compose -f compose.prod.yaml build
          docker compose -f compose.prod.yaml push
