name: Running unit/integration tests

on:
  push:
    branches:
      - main
      - next

jobs:
  tests:
    runs-on: ubuntu-latest
    # environment: test (uncomment when repo go to public)

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
      db:
        image: postgres:17
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
      AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
      JOBS_BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
      PORT: 9030
      LOG_LEVEL: silent
      JOBS_API_BASEURL: http://localhost:3090
      NEXT_PUBLIC_BASEURL: http://localhost:3000
      TEST_USERS_PASSWORD: younes

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint
        run: yarn run lint

      - name: Build
        run: yarn run build

      - name: Run integration and unit tests
        run: yarn run test
