name: Running unittest on jobs service

on:
  push:
    branches:
      - main

jobs:
  TestCore:
    runs-on: ubuntu-latest
    environment: test
    services:
      db:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          - 5432:5432
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
      PORT: ${{ env.PORT }}
      LOG_LEVEL: ${{ env.LOG_LEVEL }}
      AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
      JOBS_BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
      JOBS_API_BASEURL: ${{ env.JOBS_API_BASEURL }}
      NEXT_PUBLIC_BASEURL: ${{ env.NEXT_PUBLIC_BASEURL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint
        run: turbo lint

      - name: Migrate database
        run: turbo run migrate --filter=@delivery/jobs

      - name: Run e2e/unit tests
        run: turbo test
