name: Running UT/E2E and IT tests on jobs service

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    environment: test

    services:
      db:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          - 5432:5432
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
      AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
      JOBS_BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
      PORT: 9030
      LOG_LEVEL: silent
      JOBS_API_BASEURL: http://localhost:3090
      NEXT_PUBLIC_BASEURL: http://localhost:3000

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: Clean up database
        if: always()
        run: |
          PGPASSWORD=postgres psql -h localhost -U postgres -d postgres -c "TRUNCATE TABLE system_config, users, github_app_secret, github_app, applications, environment_variables, application_environment_variables CASCADE;"

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint
        run: yarn run lint

      - name: Build
        run: yarn run build

      - name: Migrate database
        run: yarn run migrate

      - name: Run e2e/unit tests
        run: yarn run test
