name: Running unit/integration tests

on:
  push:
    branches:
      - main
      - next

jobs:
  tests:
    runs-on: ubuntu-latest
    environment: test

    services:
      screenshots-storage:
        image: bitnami/minio:latest
        ports:
          - 9000:9000
          - 9001:9001
        env:
          MINIO_ROOT_USER: younes
          MINIO_ROOT_PASSWORD: LJHSDF6DFCG2545xxDFG7SDFGd6
          MINIO_SERVER_ACCESS_KEY: younes
          MINIO_SERVER_SECRET_KEY: LJIhjkhgjHGJhjkJKL6515561jku
          MINIO_DEFAULT_BUCKETS: screenshots:public
          MINIO_ENDPOINT: http://localhost
        volumes:
          - ${{ github.workspace }}/data:/data
        options: --name=minio --health-cmd "curl http://localhost:9000/minio/health/live"
      redis:
        image: redis
        ports:
          - 6379:6379
      db:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
    env:
      DOTENV_PRIVATE_KEY_JOBS_CI: ${{ secrets.DOTENV_PRIVATE_KEY_JOBS_CI }}
      DOTENV_PRIVATE_KEY_WEB_CI: ${{ secrets.DOTENV_PRIVATE_KEY_WEB_CI }}
      DOTENV_PRIVATE_KEY: ${{ DOTENV_PRIVATE_KEY }}

    steps:
      - run: curl -sfS https://dotenvx.sh/install.sh | sh
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint
        run: yarn run lint

      - name: Build
        run: yarn run build

      - name: Run integration and unit tests
        run: yarn run test
