name: Minimal CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.19.1]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
        env:
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          LOG_LEVEL: ${{ env.LOG_LEVEL }}
          NODE_ENV: ${{ env.NODE_ENV }}
          PORT: ${{ env.PORT }}
      - run: yarn install
      - run: yarn test
