name: Running unittest on jobs service

on:
  push:
    paths:
      - 'apps/jobs/src/**'

jobs:
  Test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    env:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
      BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
      NODE_ENV: test
      PORT: 3090
      LOG_LEVEL: silent

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install --frozen-lockfile --non-interactive --prefer-offline

      - name: Lint
        run: yarn workspace @delivery/jobs run lint

      - name: Migrate database
        run: yarn workspace @delivery/jobs run migrate

      - name: Run the unitesting
        run: yarn workspace @delivery/jobs run test
